### ISSUE TITLE
Fullscreen is pointless + camera drift + starting text dissapeared immediately

### ISSUE THREAD

**Issue by yonatan-ratner** [OM2-WayOfTheNinja/Way-Of-The-Ninja#1]
like title says, after the game loads i can see some windows (which are too condensed IMO) and these disappear basically the frame after.

**Comment by Maor-Or** [comment]
שינינו את גודל המשחק כך שיהיה רוחב 1920 על אורך 1080, כך שהגדלת המסך מתאימה. סידרנו את החלון הקופץ שמסביר על תזוזה בסיסית של המשחק
