### ISSUE TITLE
הסיבוב של המצלמה מהיר מדי

### ISSUE THREAD

**Issue by erelsgl** [OM2-WayOfTheNinja/Way-Of-The-Ninja#2]
כשאני מזיז את העכבר, לפעמים המצלמה מסתובבת מהר מדי ואני פתאום רואה את התקרה - זה מבלבל. הנה דוגמה מאולם האימונים:

![image](https://github.com/OM2-WayOfTheNinja/Way-Of-The-Ninja/assets/1462215/ca564db2-01eb-43a4-a53d-0ebc182a528d)

אולי תוסיפו בקוד מגבלה - שלא יהיה אפשר לסובב את המצלמה יותר מדי למעלה - כך שהשחקן לא ירגיש שהוא "הפוך".

**Comment by Maor-Or** [comment]
הקטנו את מהירות המצלמה, שיפרנו מעט את הקוד של תנועת המצלמה והגבלנו את היכולת להרים את ראש השחקן עד למעלה בכמה מעלות. בנוסף הוספנו את האפשרות ב"settings" כאשר עוצרים את המשחק בכל שלב להנמיך את מהירות המצלמה בהתאם.
