### ISSUE TITLE
תנו משוב חיובי לשחקן שמצליח במשימה

### ISSUE THREAD

**Issue by erelsgl** [OM2-WayOfTheNinja/Way-Of-The-Ninja#3]
אחרי ששחקן הצליח במשימה, לפני שעוברים למשימה הבאה, תנו לו משוב חיובי (לדוגמה, שהמאסטר יגיד לו "כל הכבוד"), וכמה שניות לנשום לפני המשימה הבאה.

**Comment by Maor-Or** [comment]
הוספנו על כל הצלחה במשימה צליל וטקסט שנותנים משוב חיובי, וכל הכבוד מהמאסטר, עם מרווח בין משימות
