### ISSUE TITLE
במסך הפתיחה לא לגמרי ברור לאן צריך ללכת

### ISSUE THREAD

**Issue by erelsgl** [OM2-WayOfTheNinja/Way-Of-The-Ninja#4]
העין שלי נמשכה למקום הזה, שיש בו פתח בקיר:

![image](https://github.com/OM2-WayOfTheNinja/Way-Of-The-Ninja/assets/1462215/4c6e7a2b-de09-47b0-815a-de13b0ae89ea)

אבל מתברר שדווקא שם אי אפשר לעבור, צריך ללכת לצד שני:

![image](https://github.com/OM2-WayOfTheNinja/Way-Of-The-Ninja/assets/1462215/fe9826f7-395c-4797-8e5d-5ab0321ddd3c)

נסו לעצב את הסצינה הזאת כך שיהיה ברור יותר לשחקן לאן הוא צריך ללכת - חבל שייתקע כבר בהתחלה..

**Comment by Maor-Or** [comment]
סגרנו את החור מהתמונה הראשונה והוספנו שילוט מתאים
